# Generated by Django 6.0.1 on 2026-01-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
